version: '2'

services:
    kafka-cluster:
      image: landoop/fast-data-dev:latest
      environment:
        ADV_HOST: 127.0.0.1
        RUNTESTS: 0
      ports:
        - 2181:2181
        - 3030:3030
        - 8081-8083:8081-8083
        - 9581-9585:9581-9585
        - 9092:9092
    elasticsearch:
      image: nshou/elasticsearch-kibana:latest
      ports:
        - 9200:9200
        - 5600:5600
    postgres:
      image: postgres:9.5-alpine
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      ports:
        - 5432:5432
